In [1]:
import pandas as pd
import numpy as np

C:\Users\Admin\anaconda3\lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
C:\Users\Admin\anaconda3\lib\site-packages\numpy\.libs\libopenblas.FB5AE2TYXYH2IJRDKGDGQ3XBKLKTF43H.gfortran-win_amd64.dll
C:\Users\Admin\anaconda3\lib\site-packages\numpy\.libs\libopenblas.PYQHXLVVQ7VESDPUVUADXEVJOBGHJPAY.gfortran-win_amd64.dll
  warnings.warn("loaded more than 1 DLL from .libs:"

In [2]:
df = pd.read_csv('cleanedData.csv')

In [3]:
# Change categorical string to array
df['genres'] = df['genres'].apply(lambda x: x.split(","))

In [4]:
y = []
x = {}
for item in df['genres']:
    y.append(len(item))
    for cat in item:
        x[cat] = '1'
        
# Maximum length of genres in one data
max(y)

3

In [5]:
# All unique genres
x.keys()

dict_keys(['Drama', 'Action', 'Adventure', 'Biography', 'Fantasy', 'Comedy', 'War', 'Documentary', 'Crime', 'Romance', 'Family', 'History', 'Sci-Fi', 'Thriller', 'Western', 'Sport', 'Mystery', 'Horror', 'Music', 'Animation', 'Musical', 'Film-Noir', 'News', 'Short', 'Adult', 'Reality-TV', 'Talk-Show', 'Game-Show'])

In [6]:
# All number of unique genres
len(x.keys())

28

In [9]:
# Cast it to a dictionary
catDict = {element: idx+1 for idx, element in enumerate(x)}
print(catDict)

{'Drama': 1, 'Action': 2, 'Adventure': 3, 'Biography': 4, 'Fantasy': 5, 'Comedy': 6, 'War': 7, 'Documentary': 8, 'Crime': 9, 'Romance': 10, 'Family': 11, 'History': 12, 'Sci-Fi': 13, 'Thriller': 14, 'Western': 15, 'Sport': 16, 'Mystery': 17, 'Horror': 18, 'Music': 19, 'Animation': 20, 'Musical': 21, 'Film-Noir': 22, 'News': 23, 'Short': 24, 'Adult': 25, 'Reality-TV': 26, 'Talk-Show': 27, 'Game-Show': 28}

In [8]:
import json 

# Serializing json
json_object = json.dumps(catDict, indent=4)
 
# Writing to genres.json
with open("genres.json", "w") as outfile:
    outfile.write(json_object)

In [12]:
genres = df['genres'].apply(lambda x: [catDict[i] for i in x]).to_list()

In [18]:
tempGenreArr = []
for row in genres:
    x = np.zeros(28)
    for genre in row:
        x[genre - 1] = 1
    tempGenreArr.append(x)

In [34]:
transformedGenres = \
pd.DataFrame(tempGenreArr, columns=["genre"+element for idx, element in enumerate(catDict)])

In [36]:
df = pd.concat([df.reset_index(), transformedGenres], axis=1)

In [39]:
df.head()

,index,tconst,isAdult,startYear,genres,directors,genreDrama,genreAction,genreAdventure,genreBiography,...,genreMusic,genreAnimation,genreMusical,genreFilm-Noir,genreNews,genreShort,genreAdult,genreReality-TV,genreTalk-Show,genreGame-Show
0,0,tt0000502,0,1905,[Drama],nm0063413,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1,tt0000574,0,1906,"[Action, Adventure, Biography]",nm0846879,0.0,1.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2,tt0000591,0,1907,[Drama],nm0141150,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,3,tt0000615,0,1907,[Drama],nm0533958,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,4,tt0000630,0,1908,[Drama],nm0143333,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [40]:
df = df.drop(['index'], axis=1)

In [41]:
# Appply same dunction to directors column
# Change categorical string to array
df['directors'] = df['directors'].apply(lambda x: x.split(","))

In [42]:
y = []
x = {}
for item in df['directors']:  
    y.append(len(item))
    for cat in item:
        x[cat] = '1'

In [43]:
# Maximum length of directors in one row of data
max(y)

87

In [44]:
tfArr = df['directors'].apply(lambda x: len(x) < 4)

In [45]:
df = df.loc[tfArr]

In [46]:
df.shape

(546543, 33)

In [47]:
# Cast it to a dictionary
directorsDict = {element: idx+1 for idx, element in enumerate(x)}
directorsDict

{'nm0063413': 1,
 'nm0846879': 2,
 'nm0141150': 3,
 'nm0533958': 4,
 'nm0143333': 5,
 'nm0194088': 6,
 'nm0091767': 7,
 'nm0877783': 8,
 'nm0081288': 9,
 'nm0691994': 10,
 'nm0185426': 11,
 'nm0017074': 12,
 'nm0005717': 13,
 'nm0023107': 14,
 'nm0550220': 15,
 'nm0878467': 16,
 'nm0099901': 17,
 'nm0294276': 18,
 'nm0022607': 19,
 'nm0826298': 20,
 'nm0923603': 21,
 'nm0159015': 22,
 'nm0375839': 23,
 'nm0605942': 24,
 'nm0666972': 25,
 'nm0130633': 26,
 'nm0693516': 27,
 'nm0580197': 28,
 'nm0088881': 29,
 'nm0169878': 30,
 'nm0085865': 31,
 'nm0471787': 32,
 'nm1024681': 33,
 'nm0135052': 34,
 'nm1159832': 35,
 'nm0764002': 36,
 'nm0182052': 37,
 'nm0001908': 38,
 'nm0108345': 39,
 'nm0205986': 40,
 'nm0408436': 41,
 'nm1267460': 42,
 'nm0738202': 43,
 'nm0118272': 44,
 'nm0736464': 45,
 'nm0519315': 46,
 'nm0300487': 47,
 'nm0949565': 48,
 'nm0388674': 49,
 'nm0288616': 50,
 'nm0611814': 51,
 'nm0511143': 52,
 'nm0511729': 53,
 'nm0727484': 54,
 'nm0087250': 55,
 'nm0350695': 56,
 'nm0325670': 57,
 'nm0168503': 58,
 'nm0698839': 59,
 'nm0259235': 60,
 'nm0448682': 61,
 'nm0949648': 62,
 'nm0351331': 63,
 'nm0851633': 64,
 'nm0309130': 65,
 'nm0078205': 66,
 'nm0209738': 67,
 'nm0655824': 68,
 'nm0884879': 69,
 'nm0773654': 70,
 'nm0488932': 71,
 'nm0823150': 72,
 'nm0511155': 73,
 'nm0646058': 74,
 'nm0227602': 75,
 'nm0000428': 76,
 'nm0304098': 77,
 'nm0127511': 78,
 'nm0002031': 79,
 'nm0072872': 80,
 'nm0523932': 81,
 'nm0345500': 82,
 'nm0218404': 83,
 'nm0443857': 84,
 'nm1824687': 85,
 'nm0881638': 86,
 'nm0830249': 87,
 'nm0582268': 88,
 'nm0419327': 89,
 'nm0296193': 90,
 'nm0753233': 91,
 'nm0334918': 92,
 'nm0533048': 93,
 'nm0858501': 94,
 'nm0316794': 95,
 'nm0806961': 96,
 'nm0215516': 97,
 'nm0803705': 98,
 'nm0354845': 99,
 'nm0869665': 100,
 'nm0233626': 101,
 'nm0878069': 102,
 'nm0191133': 103,
 'nm0325448': 104,
 'nm0692105': 105,
 'nm0205653': 106,
 'nm0532622': 107,
 'nm0354790': 108,
 'nm6955979': 109,
 'nm0146957': 110,
 'nm0838052': 111,
 'nm0275421': 112,
 'nm0085133': 113,
 'nm0823088': 114,
 'nm0029253': 115,
 'nm0938041': 116,
 'nm0674398': 117,
 'nm0883920': 118,
 'nm0687575': 119,
 'nm0720862': 120,
 'nm0403439': 121,
 'nm0330280': 122,
 'nm0870831': 123,
 'nm0718121': 124,
 'nm0107543': 125,
 'nm0306723': 126,
 'nm0774256': 127,
 'nm0903249': 128,
 'nm0601190': 129,
 'nm0662442': 130,
 'nm0738109': 131,
 'nm0099754': 132,
 'nm0551361': 133,
 'nm0176699': 134,
 'nm0532349': 135,
 'nm0285684': 136,
 'nm0276165': 137,
 'nm0048478': 138,
 'nm0408433': 139,
 'nm0915270': 140,
 'nm2297223': 141,
 'nm0250480': 142,
 'nm0551375': 143,
 'nm0376529': 144,
 'nm0098376': 145,
 'nm0853193': 146,
 'nm0349785': 147,
 'nm0748272': 148,
 'nm0159654': 149,
 'nm0596218': 150,
 'nm0643290': 151,
 'nm0917467': 152,
 'nm0066734': 153,
 'nm0641967': 154,
 'nm0699392': 155,
 'nm0875869': 156,
 'nm0734958': 157,
 'nm0643138': 158,
 'nm2827911': 159,
 'nm0235121': 160,
 'nm0933406': 161,
 'nm0713787': 162,
 'nm0365493': 163,
 'nm0283766': 164,
 'nm0136888': 165,
 'nm0289797': 166,
 'nm0403054': 167,
 'nm0838074': 168,
 'nm0455544': 169,
 'nm0345217': 170,
 'nm0813682': 171,
 'nm0569261': 172,
 'nm0309186': 173,
 'nm0764090': 174,
 'nm0865601': 175,
 'nm0373614': 176,
 'nm0927468': 177,
 'nm0186345': 178,
 'nm0078116': 179,
 'nm0784988': 180,
 'nm0213108': 181,
 'nm0743047': 182,
 'nm0352726': 183,
 'nm0054977': 184,
 'nm0281621': 185,
 'nm0466099': 186,
 'nm0956428': 187,
 'nm0456804': 188,
 'nm0360114': 189,
 'nm0424530': 190,
 'nm0694640': 191,
 'nm0491503': 192,
 'nm0577654': 193,
 'nm0228512': 194,
 'nm0923594': 195,
 'nm0821472': 196,
 'nm0002177': 197,
 'nm0001124': 198,
 'nm0132324': 199,
 'nm0426310': 200,
 'nm0665163': 201,
 'nm0836316': 202,
 'nm0167633': 203,
 'nm0507150': 204,
 'nm0861002': 205,
 'nm0616729': 206,
 'nm0533158': 207,
 'nm0245385': 208,
 'nm0853336': 209,
 'nm0725529': 210,
 'nm0695466': 211,
 'nm0410271': 212,
 'nm0036048': 213,
 'nm0856161': 214,
 'nm0533289': 215,
 'nm0170973': 216,
 'nm0526226': 217,
 'nm0509287': 218,
 'nm0674600': 219,
 'nm0621797': 220,
 'nm0426754': 221,
 'nm0357872': 222,
 'nm0782707': 223,
 'nm0309163': 224,
 'nm0098308': 225,
 'nm0780884': 226,
 'nm0888428': 227,
 'nm0928910': 228,
 'nm0237713': 229,
 'nm0608108': 230,
 'nm0198523': 231,
 'nm0145924': 232,
 'nm0765106': 233,
 'nm0707778': 234,
 'nm0301961': 235,
 'nm0603050': 236,
 'nm0024464': 237,
 'nm0897085': 238,
 'nm0540575': 239,
 'nm0403636': 240,
 'nm0391847': 241,
 'nm0204724': 242,
 'nm0569645': 243,
 'nm5177136': 244,
 'nm0681151': 245,
 'nm0159725': 246,
 'nm0002061': 247,
 'nm0531759': 248,
 'nm0041858': 249,
 'nm0276578': 250,
 'nm0576901': 251,
 'nm0922304': 252,
 'nm0916665': 253,
 'nm0937628': 254,
 'nm0137407': 255,
 'nm0531940': 256,
 'nm0773303': 257,
 'nm0639631': 258,
 'nm0193327': 259,
 'nm0206619': 260,
 'nm0868114': 261,
 'nm0269265': 262,
 'nm0370746': 263,
 'nm0227020': 264,
 'nm0652650': 265,
 'nm0636076': 266,
 'nm0909825': 267,
 'nm0250053': 268,
 'nm0063612': 269,
 'nm0694534': 270,
 'nm0861527': 271,
 'nm0941782': 272,
 'nm0679170': 273,
 'nm0285643': 274,
 'nm0085877': 275,
 'nm0102643': 276,
 'nm0790348': 277,
 'nm0935488': 278,
 'nm0002503': 279,
 'nm0502752': 280,
 'nm0115450': 281,
 'nm1250355': 282,
 'nm0806565': 283,
 'nm0360617': 284,
 'nm0593010': 285,
 'nm0301252': 286,
 'nm0007221': 287,
 'nm0258197': 288,
 'nm0872868': 289,
 'nm0621817': 290,
 'nm0855912': 291,
 'nm2542573': 292,
 'nm0713223': 293,
 'nm0562004': 294,
 'nm0303120': 295,
 'nm0941388': 296,
 'nm0390479': 297,
 'nm0819384': 298,
 'nm0061955': 299,
 'nm0205601': 300,
 'nm0012416': 301,
 'nm0130797': 302,
 'nm0210352': 303,
 'nm0296703': 304,
 'nm0624601': 305,
 'nm0359687': 306,
 'nm0707095': 307,
 'nm0394524': 308,
 'nm0247107': 309,
 'nm0631438': 310,
 'nm0119138': 311,
 'nm0571760': 312,
 'nm0009257': 313,
 'nm1868732': 314,
 'nm0669260': 315,
 'nm0290822': 316,
 'nm0483022': 317,
 'nm0187006': 318,
 'nm0560785': 319,
 'nm0339765': 320,
 'nm0377053': 321,
 'nm0892185': 322,
 'nm0633605': 323,
 'nm0784407': 324,
 'nm0071658': 325,
 'nm0524306': 326,
 'nm0534288': 327,
 'nm0789748': 328,
 'nm0800480': 329,
 'nm0381178': 330,
 'nm0327201': 331,
 'nm0352461': 332,
 'nm0770846': 333,
 'nm0280463': 334,
 'nm0624735': 335,
 'nm0833641': 336,
 'nm0532072': 337,
 'nm0803929': 338,
 'nm0912844': 339,
 'nm0082914': 340,
 'nm0515979': 341,
 'nm0912817': 342,
 'nm0587929': 343,
 'nm0684741': 344,
 'nm0950148': 345,
 'nm0822801': 346,
 'nm0842521': 347,
 'nm0165843': 348,
 'nm0118523': 349,
 'nm0331084': 350,
 'nm0613966': 351,
 'nm0461295': 352,
 'nm0000252': 353,
 'nm0154352': 354,
 'nm0553320': 355,
 'nm0378408': 356,
 'nm0395023': 357,
 'nm0169995': 358,
 'nm0107838': 359,
 'nm0005847': 360,
 'nm0430968': 361,
 'nm0366586': 362,
 'nm0102783': 363,
 'nm0053425': 364,
 'nm0869421': 365,
 'nm0191605': 366,
 'nm0208657': 367,
 'nm0881616': 368,
 'nm0532023': 369,
 'nm0048864': 370,
 'nm0504353': 371,
 'nm0593180': 372,
 'nm0717046': 373,
 'nm0244180': 374,
 'nm0796657': 375,
 'nm0012317': 376,
 'nm0594291': 377,
 'nm0172413': 378,
 'nm0234149': 379,
 'nm0822219': 380,
 'nm0235791': 381,
 'nm0011840': 382,
 'nm0531866': 383,
 'nm0665737': 384,
 'nm0408429': 385,
 'nm0930198': 386,
 'nm0111753': 387,
 'nm0148546': 388,
 'nm0124919': 389,
 'nm0725893': 390,
 'nm0413045': 391,
 'nm0807742': 392,
 'nm0226992': 393,
 'nm0070374': 394,
 'nm0033975': 395,
 'nm0250445': 396,
 'nm0428013': 397,
 'nm0767303': 398,
 'nm10753623': 399,
 'nm0296249': 400,
 'nm0496475': 401,
 'nm0585495': 402,
 'nm0367556': 403,
 'nm0408937': 404,
 'nm0256221': 405,
 'nm0629589': 406,
 'nm0689471': 407,
 'nm0202573': 408,
 'nm0942396': 409,
 'nm0630799': 410,
 'nm0442180': 411,
 'nm0686421': 412,
 'nm0686859': 413,
 'nm0003193': 414,
 'nm0574431': 415,
 'nm0617020': 416,
 'nm0318397': 417,
 'nm0267922': 418,
 'nm0322794': 419,
 'nm0291548': 420,
 'nm0291387': 421,
 'nm0217557': 422,
 'nm0694260': 423,
 'nm3168648': 424,
 'nm0593309': 425,
 'nm0837442': 426,
 'nm0701709': 427,
 'nm1441208': 428,
 'nm0096705': 429,
 'nm0412257': 430,
 'nm0537207': 431,
 'nm0223267': 432,
 'nm0898660': 433,
 'nm0047426': 434,
 'nm0079974': 435,
 'nm0077928': 436,
 'nm0027992': 437,
 'nm0160280': 438,
 'nm0170863': 439,
 'nm0725944': 440,
 'nm0922959': 441,
 'nm0152826': 442,
 'nm0367745': 443,
 'nm0078340': 444,
 'nm0936767': 445,
 'nm0401967': 446,
 'nm0758441': 447,
 'nm0168504': 448,
 'nm0256438': 449,
 'nm0863237': 450,
 'nm0257574': 451,
 'nm0101413': 452,
 'nm0922928': 453,
 'nm0029525': 454,
 'nm0717281': 455,
 'nm0221142': 456,
 'nm0500226': 457,
 'nm0654581': 458,
 'nm0558236': 459,
 'nm0720531': 460,
 'nm0922192': 461,
 'nm0051140': 462,
 'nm0633583': 463,
 'nm0492773': 464,
 'nm4720696': 465,
 'nm0221741': 466,
 'nm0578507': 467,
 'nm0130791': 468,
 'nm0454771': 469,
 'nm0624511': 470,
 'nm0581653': 471,
 'nm0251456': 472,
 'nm0237710': 473,
 'nm0569466': 474,
 'nm0454535': 475,
 'nm0074325': 476,
 'nm0637463': 477,
 'nm0106990': 478,
 'nm0808403': 479,
 'nm0533539': 480,
 'nm0637507': 481,
 'nm0916904': 482,
 'nm0745527': 483,
 'nm0869645': 484,
 'nm0492742': 485,
 'nm0454545': 486,
 'nm1561233': 487,
 'nm0730170': 488,
 'nm0600580': 489,
 'nm0394743': 490,
 'nm0367542': 491,
 'nm0338458': 492,
 'nm0605034': 493,
 'nm0797094': 494,
 'nm0164030': 495,
 'nm0881553': 496,
 'nm0413573': 497,
 'nm0531691': 498,
 'nm0308257': 499,
 'nm0459319': 500,
 'nm0769144': 501,
 'nm0861336': 502,
 'nm0447178': 503,
 'nm0071992': 504,
 'nm0922386': 505,
 'nm0131085': 506,
 'nm0434058': 507,
 'nm0248940': 508,
 'nm0857222': 509,
 'nm0513617': 510,
 'nm0410174': 511,
 'nm0539718': 512,
 'nm0432216': 513,
 'nm0356818': 514,
 'nm0653253': 515,
 'nm0002271': 516,
 'nm0402489': 517,
 'nm0607940': 518,
 'nm0058792': 519,
 'nm0377126': 520,
 'nm0376221': 521,
 'nm0030748': 522,
 'nm0366689': 523,
 'nm0624714': 524,
 'nm0456634': 525,
 'nm0621020': 526,
 'nm0078442': 527,
 'nm0097648': 528,
 'nm0824660': 529,
 'nm0051019': 530,
 'nm0721840': 531,
 'nm0534221': 532,
 'nm0560543': 533,
 'nm0228746': 534,
 'nm0189076': 535,
 'nm0074112': 536,
 'nm9775302': 537,
 'nm0394399': 538,
 'nm0235278': 539,
 'nm0536355': 540,
 'nm0301131': 541,
 'nm1887049': 542,
 'nm0271717': 543,
 'nm0877478': 544,
 'nm0454870': 545,
 'nm0534957': 546,
 'nm0313373': 547,
 'nm0828381': 548,
 'nm0124279': 549,
 'nm0806143': 550,
 'nm0361882': 551,
 'nm0284960': 552,
 'nm0911959': 553,
 'nm0920384': 554,
 'nm0376396': 555,
 'nm0937581': 556,
 'nm0194453': 557,
 'nm0550892': 558,
 'nm0535957': 559,
 'nm0547975': 560,
 'nm0775416': 561,
 'nm0751510': 562,
 'nm0696106': 563,
 'nm0356731': 564,
 'nm0848211': 565,
 'nm0696049': 566,
 'nm0762677': 567,
 'nm0733208': 568,
 'nm0612076': 569,
 'nm0666835': 570,
 'nm0629243': 571,
 'nm0922300': 572,
 'nm0163540': 573,
 'nm0064508': 574,
 'nm0140562': 575,
 'nm0103853': 576,
 'nm0872813': 577,
 'nm0588056': 578,
 'nm0911353': 579,
 'nm0314700': 580,
 'nm0394742': 581,
 'nm0825225': 582,
 'nm0101038': 583,
 'nm0662006': 584,
 'nm0839828': 585,
 'nm0187981': 586,
 'nm0570985': 587,
 'nm0322843': 588,
 'nm0232063': 589,
 'nm0087658': 590,
 'nm0414985': 591,
 'nm0524784': 592,
 'nm0055011': 593,
 'nm0627274': 594,
 'nm0407778': 595,
 'nm0069373': 596,
 'nm0501902': 597,
 'nm0077162': 598,
 'nm0255980': 599,
 'nm0384616': 600,
 'nm0934010': 601,
 'nm0064600': 602,
 'nm0018437': 603,
 'nm0361518': 604,
 'nm0775788': 605,
 'nm0110432': 606,
 'nm0417905': 607,
 'nm0304843': 608,
 'nm0720886': 609,
 'nm1720536': 610,
 'nm0341185': 611,
 'nm0247358': 612,
 'nm0214924': 613,
 'nm0447917': 614,
 'nm0200667': 615,
 'nm0597597': 616,
 'nm0049995': 617,
 'nm0212914': 618,
 'nm0283444': 619,
 'nm0181942': 620,
 'nm0744504': 621,
 'nm1498787': 622,
 'nm0554802': 623,
 'nm0401081': 624,
 'nm0188105': 625,
 'nm0002179': 626,
 'nm0590694': 627,
 'nm0944369': 628,
 'nm0341486': 629,
 'nm0050846': 630,
 'nm0731910': 631,
 'nm0807871': 632,
 'nm0797301': 633,
 'nm0103755': 634,
 'nm0184782': 635,
 'nm0408863': 636,
 'nm0860077': 637,
 'nm0633394': 638,
 'nm0661844': 639,
 'nm0000406': 640,
 'nm0834496': 641,
 'nm0210171': 642,
 'nm0933368': 643,
 'nm0590205': 644,
 'nm0135922': 645,
 'nm0154267': 646,
 'nm0439208': 647,
 'nm0273203': 648,
 'nm0251622': 649,
 'nm0385171': 650,
 'nm0587754': 651,
 'nm0392709': 652,
 'nm0447043': 653,
 'nm0242139': 654,
 'nm0166730': 655,
 'nm0214496': 656,
 'nm0662032': 657,
 'nm0934749': 658,
 'nm0749484': 659,
 'nm0528064': 660,
 'nm0921244': 661,
 'nm0886754': 662,
 'nm0597995': 663,
 'nm0693492': 664,
 'nm0922286': 665,
 'nm0115218': 666,
 'nm0821500': 667,
 'nm0552228': 668,
 'nm0321088': 669,
 'nm0261455': 670,
 'nm0607378': 671,
 'nm0707564': 672,
 'nm0337586': 673,
 'nm0813603': 674,
 'nm0223460': 675,
 'nm0000859': 676,
 'nm0505354': 677,
 'nm0624756': 678,
 'nm0030742': 679,
 'nm0209162': 680,
 'nm0730743': 681,
 'nm0043881': 682,
 'nm0039021': 683,
 'nm0006276': 684,
 'nm0079490': 685,
 'nm0764338': 686,
 'nm0583851': 687,
 'nm0761244': 688,
 'nm0299059': 689,
 'nm0391440': 690,
 'nm0563997': 691,
 'nm0901502': 692,
 'nm0928108': 693,
 'nm0408932': 694,
 'nm0569153': 695,
 'nm0366950': 696,
 'nm0740246': 697,
 'nm0722800': 698,
 'nm0289806': 699,
 'nm0192062': 700,
 'nm0220705': 701,
 'nm0041001': 702,
 'nm0583462': 703,
 'nm0922327': 704,
 'nm0409859': 705,
 'nm0037060': 706,
 'nm0741082': 707,
 'nm0168239': 708,
 'nm0825523': 709,
 'nm0446017': 710,
 'nm0343041': 711,
 'nm0328088': 712,
 'nm0708673': 713,
 'nm0845254': 714,
 'nm0068696': 715,
 'nm0220230': 716,
 'nm0172293': 717,
 'nm0110979': 718,
 'nm0241273': 719,
 'nm0557472': 720,
 'nm0348998': 721,
 'nm0204677': 722,
 'nm0916113': 723,
 'nm1881532': 724,
 'nm0337395': 725,
 'nm0916177': 726,
 'nm0233159': 727,
 'nm0458837': 728,
 'nm0296023': 729,
 'nm0322595': 730,
 'nm0203191': 731,
 'nm0447217': 732,
 'nm0219685': 733,
 'nm0001196': 734,
 'nm0121485': 735,
 'nm0832584': 736,
 'nm0933045': 737,
 'nm0118266': 738,
 'nm0006252': 739,
 'nm0396616': 740,
 'nm0902120': 741,
 'nm0877199': 742,
 'nm0887965': 743,
 'nm0608000': 744,
 'nm0781601': 745,
 'nm0687031': 746,
 'nm0823969': 747,
 'nm0759253': 748,
 'nm0623417': 749,
 'nm0046082': 750,
 'nm0745063': 751,
 'nm0941637': 752,
 'nm0669411': 753,
 'nm0537510': 754,
 'nm0500749': 755,
 'nm0007973': 756,
 'nm0942413': 757,
 'nm0070251': 758,
 'nm0700003': 759,
 'nm0102908': 760,
 'nm0513509': 761,
 'nm0766705': 762,
 'nm0291438': 763,
 'nm0466113': 764,
 'nm0681726': 765,
 'nm0385963': 766,
 'nm1616238': 767,
 'nm0530573': 768,
 'nm0195624': 769,
 'nm0561739': 770,
 'nm0428059': 771,
 'nm0258134': 772,
 'nm0129143': 773,
 'nm0691996': 774,
 'nm0248738': 775,
 'nm0580648': 776,
 'nm0650270': 777,
 'nm0116307': 778,
 'nm0247484': 779,
 'nm0091380': 780,
 'nm0344660': 781,
 'nm0237693': 782,
 'nm2604278': 783,
 'nm0689808': 784,
 'nm0474487': 785,
 'nm0593392': 786,
 'nm0382034': 787,
 'nm0499245': 788,
 'nm0336910': 789,
 'nm0321652': 790,
 'nm0889772': 791,
 'nm0607864': 792,
 'nm0478303': 793,
 'nm0492844': 794,
 'nm0035037': 795,
 'nm0254826': 796,
 'nm0398446': 797,
 'nm0447094': 798,
 'nm0351458': 799,
 'nm0319401': 800,
 'nm0190516': 801,
 'nm0090534': 802,
 'nm0207107': 803,
 'nm0764182': 804,
 'nm0031134': 805,
 'nm0031153': 806,
 'nm0657841': 807,
 'nm0231060': 808,
 'nm3584392': 809,
 'nm11389006': 810,
 'nm0482254': 811,
 'nm0464647': 812,
 'nm0051260': 813,
 'nm0760547': 814,
 'nm0929649': 815,
 'nm0532185': 816,
 'nm0738082': 817,
 'nm0779999': 818,
 'nm0287593': 819,
 'nm0291838': 820,
 'nm0242412': 821,
 'nm0896542': 822,
 'nm0002233': 823,
 'nm0398464': 824,
 'nm0871472': 825,
 'nm0626455': 826,
 'nm0329573': 827,
 'nm0657928': 828,
 'nm0359002': 829,
 'nm0244340': 830,
 'nm0115649': 831,
 'nm0138156': 832,
 'nm0938876': 833,
 'nm0058022': 834,
 'nm0587277': 835,
 'nm0289741': 836,
 'nm1509890': 837,
 'nm0065215': 838,
 'nm0895048': 839,
 'nm0245213': 840,
 'nm0000485': 841,
 'nm0447636': 842,
 'nm0219832': 843,
 'nm0054011': 844,
 'nm0581683': 845,
 'nm0382730': 846,
 'nm0677893': 847,
 'nm0766581': 848,
 'nm0243295': 849,
 'nm0156311': 850,
 'nm0349180': 851,
 'nm0003638': 852,
 'nm0206031': 853,
 'nm0462113': 854,
 'nm0750979': 855,
 'nm0920243': 856,
 'nm0085870': 857,
 'nm0604679': 858,
 'nm0133153': 859,
 'nm0216941': 860,
 'nm0516974': 861,
 'nm0464137': 862,
 'nm0304569': 863,
 'nm0418131': 864,
 'nm0470307': 865,
 'nm0343650': 866,
 'nm0344583': 867,
 'nm0523326': 868,
 'nm0272889': 869,
 'nm0469170': 870,
 'nm0280205': 871,
 'nm0952499': 872,
 'nm0122210': 873,
 'nm0076368': 874,
 'nm0474631': 875,
 'nm0390041': 876,
 'nm0003433': 877,
 'nm0549474': 878,
 'nm0879094': 879,
 'nm0007606': 880,
 'nm0453421': 881,
 'nm0754766': 882,
 'nm0208113': 883,
 'nm0167032': 884,
 'nm0932588': 885,
 'nm0909648': 886,
 'nm0332045': 887,
 'nm0942428': 888,
 'nm0562400': 889,
 'nm0138251': 890,
 'nm0585785': 891,
 'nm0397813': 892,
 'nm0915245': 893,
 'nm0941562': 894,
 'nm0680037': 895,
 'nm0244244': 896,
 'nm0891998': 897,
 'nm0783369': 898,
 'nm0281808': 899,
 'nm0148920': 900,
 'nm0168771': 901,
 'nm0311946': 902,
 'nm0236245': 903,
 'nm0688543': 904,
 'nm0160297': 905,
 'nm0508155': 906,
 'nm0281383': 907,
 'nm0281389': 908,
 'nm0825596': 909,
 'nm0275494': 910,
 'nm2040774': 911,
 'nm0745577': 912,
 'nm0907885': 913,
 'nm0678483': 914,
 'nm0731153': 915,
 'nm0211434': 916,
 'nm1848008': 917,
 'nm0806605': 918,
 'nm0314296': 919,
 'nm0596410': 920,
 'nm0057136': 921,
 'nm0132720': 922,
 'nm0901632': 923,
 'nm0373367': 924,
 'nm0939992': 925,
 'nm0803271': 926,
 'nm0367314': 927,
 'nm0020923': 928,
 'nm0057767': 929,
 'nm0393042': 930,
 'nm0269493': 931,
 'nm0249772': 932,
 'nm0002209': 933,
 'nm0144951': 934,
 'nm0181548': 935,
 'nm0373511': 936,
 'nm0448915': 937,
 'nm0336894': 938,
 'nm0008776': 939,
 'nm0194098': 940,
 'nm0796636': 941,
 'nm0529047': 942,
 'nm0602905': 943,
 'nm0178107': 944,
 'nm0106950': 945,
 'nm0781292': 946,
 'nm0916224': 947,
 'nm0308593': 948,
 'nm0452432': 949,
 'nm0392747': 950,
 'nm0843364': 951,
 'nm0713673': 952,
 'nm0113284': 953,
 'nm0377400': 954,
 'nm0552609': 955,
 'nm0104197': 956,
 'nm0147391': 957,
 'nm0942048': 958,
 'nm0222401': 959,
 'nm0166700': 960,
 'nm0763453': 961,
 'nm0778218': 962,
 'nm0647652': 963,
 'nm0782682': 964,
 'nm0902006': 965,
 'nm0652302': 966,
 'nm0194806': 967,
 'nm0827717': 968,
 'nm0653288': 969,
 'nm0286379': 970,
 'nm0299154': 971,
 'nm0761770': 972,
 'nm0662840': 973,
 'nm0919976': 974,
 'nm0003373': 975,
 'nm0673027': 976,
 'nm0738203': 977,
 'nm0298291': 978,
 'nm2233714': 979,
 'nm0217615': 980,
 'nm0073239': 981,
 'nm0814027': 982,
 'nm0617276': 983,
 'nm0071665': 984,
 'nm0943313': 985,
 'nm0525414': 986,
 'nm0646902': 987,
 'nm1253778': 988,
 'nm0075960': 989,
 'nm0144863': 990,
 'nm0059648': 991,
 'nm0199003': 992,
 'nm0753697': 993,
 'nm0099230': 994,
 'nm0589616': 995,
 'nm0209558': 996,
 'nm0615736': 997,
 'nm0001273': 998,
 'nm1252728': 999,
 'nm0195950': 1000,
 ...}

In [23]:
# Serializing json
json_object = json.dumps(directorsDict, indent=4)
 
# Writing to directors.json
with open("directors.json", "w") as outfile:
    outfile.write(json_object)

In [48]:
len(directorsDict)

230895

In [49]:
directors = \
pd.DataFrame(df['directors'].apply(\
    lambda x: [\
    directorsDict[i] for i in x]).to_list(), columns=['dir1', 'dir2', 'dir3'])

In [50]:
directors

          dir1     dir2  dir3
0            1      NaN   NaN
1            2      NaN   NaN
2            3      NaN   NaN
3            4      NaN   NaN
4            5      NaN   NaN
...        ...      ...   ...
546538  230894  63957.0   NaN
546539   29071      NaN   NaN
546540  196384      NaN   NaN
546541  230895      NaN   NaN
546542   63957  65481.0   NaN

[546543 rows x 3 columns]

In [51]:
df = pd.concat([df.reset_index(), directors], axis=1)

In [52]:
df.loc[:,['dir1', 'dir2', 'dir3']] = \
df.loc[:,['dir1', 'dir2', 'dir3']].fillna(0)

In [34]:
df.drop(['genre1', 'genre2', 'genre3', 'dir1', 'dir2', 'dir3', 'index', 'tconst'], axis=1).to_csv('detailsDataset.csv', index=False)

In [56]:
finaldf = df.drop(['genres', 'directors', 'index', 'tconst'], axis=1)

In [57]:
finaldf.head()

,isAdult,startYear,genreDrama,genreAction,genreAdventure,genreBiography,genreFantasy,genreComedy,genreWar,genreDocumentary,...,genreFilm-Noir,genreNews,genreShort,genreAdult,genreReality-TV,genreTalk-Show,genreGame-Show,dir1,dir2,dir3
0,0,1905,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,0.0,0.0
1,0,1906,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2,0.0,0.0
2,0,1907,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3,0.0,0.0
3,0,1907,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4,0.0,0.0
4,0,1908,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5,0.0,0.0

In [58]:
finaldf.to_csv('finalDataset.csv', index=False)